Fixes on CI

diff --git a/.github/workflows/publish.yaml b/.github/workflows/publish.yaml
--- a/.github/workflows/publish.yaml
+++ b/.github/workflows/publish.yaml
@@ -14,17 +14,17 @@ jobs:
         uses: actions/checkout@v6
       - name: Check tag format
         run: |
-          if [[ ! "${GITHUB_REF#refs/tags/}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
-            echo "Tag name does not match semantic versioning format vX.Y.Z"
+          if [[ ! "${GITHUB_REF}" =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+            echo "Tag ${GITHUB_REF} does not match required format vX.Y.Z"
             exit 1
           fi
       
       - name: Check main branch
         run: |
-          LATEST_COMMIT=$(git rev-parse HEAD)
-          MAIN_COMMIT=$(git rev-parse origin/main)
-          if [ "$LATEST_COMMIT" != "$MAIN_COMMIT" ]; then
-            echo "The tag must be created from the latest commit on the main branch."
+          git fetch origin main
+
+          if ! git merge-base --is-ancestor ${GITHUB_SHA} origin/main; then
+            echo "Tag ${GITHUB_REF} is not based on the latest main branch"
             exit 1
           fi
 
